### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by paulz1** [rocky-linux/rockylinux.org#16]
Not sure if it's the right place to post this issue, but in doubt let's start from here.

It seems that rss feed of rockylinux.org stops working.

No feed in thunderbird (and alert icon with exclamation mark). And the url [https://rockylinux.org/rss.xml](https://rockylinux.org/rss.xml) seems to be empty.

**Comment by FoggyMtnDrifter** [comment]
Hey there! Thanks for the report.

This should now be fixed. Please let us know if you have issues with it.
