### ISSUE TITLE
Squished support, sponsor, and partners logos

### ISSUE THREAD

**Issue by jonasrosland** [rocky-linux/rockylinux.org#18]
Great job on the new site! It looks great.
One thing I saw was that a few of the logos are squished.

https://rockylinux.org/support/support-providers
* CIQ

https://rockylinux.org/about/partners
* CIQ
* NAVER Cloud
* Fastly
* OSSLAB
* Supermicro

https://rockylinux.org/about/sponsors
* CIQ
* OpenDrives
* Rakuten Symphony
* Missing logos for OpenLogic, ProComputers, and Seagate Federal

**Comment by FoggyMtnDrifter** [comment]
What browser and platform are you seeing this in? I'm not seeing any squished logos in Chromium or Firefox.

The omission of logos for some sponsors/partners is intentional due to their tier. We weren't enforcing that previously but decided to do so going forward.

**Comment by FoggyMtnDrifter** [comment]
Someone on the team was able to re-produce with WebKit/Safari. I will debug this later tonight. Thanks for the report!
