### ISSUE TITLE
[BUG] redirect /cloud-images to /download

### ISSUE THREAD

**Issue by NeilHanlon** [rocky-linux/rockylinux.org#24]
### To Reproduce

we have a lot of links and SEO pointing to /cloud-images, but we've now moved them primarily to the /downloads page.

### Expected Behavior

/cloud-images redirects to /downloads, or has content available

### Device

Desktop/Laptop

### Browser

Blink (Chromium)

### Operating System

n/a

**Comment by NebraskaCoder** [comment]
Fix has been pushed to site.
