### ISSUE TITLE
[BUG] Missing trademark guidelines 

### ISSUE THREAD

**Issue by NeilHanlon** [rocky-linux/rockylinux.org#27]
### To Reproduce

https://rockylinux.org/trademark

### Expected Behavior

Old site had these added, but I think it was after the new site began...

### Device

Desktop/Laptop

### Browser

Blink (Chromium)

### Operating System

n/a

**Comment by FoggyMtnDrifter** [comment]
They're now located here: https://rockylinux.org/legal/trademarks

Perhaps we should add a redirect?

**Comment by FoggyMtnDrifter** [comment]
To clarify, the link I provided is located in the footer.

**Comment by NeilHanlon** [comment]
Ah, yes. A redirect would be good. Looks like we have links back to this
