### ISSUE TITLE
Can we use Quart/Flask/Django instead for this?

### ISSUE THREAD

**Issue by cheesycod** [rocky-linux/rockylinux.org#5]
I think Quart/Flask/Django would be a better fit especially if we one day wanted this to become a dynamic webpage

**Comment by pxdnbluesoul** [comment]
https://github.com/rocky-linux/rockylinux.org-next is the dynamic site, this one I believe is intended to be static.

**Comment by hbjydev** [comment]
@pxdnbluesoul is right here, this site will be statically generated. Potentially, we might build a dynamic site as a blog or something, but that will likely get its own subdomain now.
