### ISSUE TITLE
WeblateOrg for translations

### ISSUE THREAD

**Issue by domingoruiz** [rocky-linux/rockylinux.org#60]
Hi. I have been searching the internet and I have found a free application that could help us with translations. This is WeblateOrg and I think it would be worth taking a look at it.
[https://github.com/WeblateOrg/weblate](https://github.com/WeblateOrg/weblate)

**Comment by ressonix** [comment]
I believe it was decided in Slack not to use one right now, but it might come in handy since we have tons of translations coming in and have some disputes about them.

**Comment by ressonix** [comment]
I see someone else mentioned this in a comment on  #55 and it appears that's what Fedora is using for theirs. What are your thoughts on the matter @hbjydev? It still might be too early for it, but this looks like a good option considering it's open-source.

**Comment by fabaff** [comment]
I think weblate could be a way to go as the Fedora Project is using it and Fedora is the upstream. I mentioned some projects in the [forum](https://forums.rockylinux.org/t/about-the-localization-category/473/3?u=fab) which are using different solutions.

The Fedora Project started with `cvs` and `intltool`, went to Transifex, Zanata and is using weblate now.

I agree with @ressonix that this should be discussed.

**Comment by ressonix** [comment]
I'm going to convert this to a discussion, as it feels better suited for that at the moment.
